const internation = {
    // common
    Close: '关闭',
    Search: '搜索',
    'About Ghost': '关于Ghost',
    'Your Profile': '账号资料',
    'Support Center': '支持中心',
    'How to Use Ghost': '怎么使用Ghost',
    'Sign Out': '登出',
    Team: '团队',
    Subscribers: '订阅者',
    General: '通用',
    Settings: '设置',
    Design: '设计',
    Tags: '标签',
    'Code injection': '代码注入',
    Integrations: '整合',
    Labs: '实验室',
    'View site': '访问网站',
    Content: '内容',
    More: '更多',
    //sign in
    Forgot: '忘记密码',
    'Email Address': '邮箱地址',
    Password: '密码',
    'Sign in': '登录',
    // post
    Stories: '文章',
    'New story': '新建文章',
    'Your stories': '你的文章',
    'All posts': '所有文章',
    'Draft posts': '草稿',
    'Published posts': '已发布文章',
    'Scheduled posts': '定时发布文章',
    'Featured posts': '专题文章',
    'Post Settings': '文章设置',
    Page: '页面',
    Draft: '草稿',
    Featured: '专题',
    by: '由',

    'All authors': '所有作者',
    Pages: '页面',
    'All tags': '所有标签',
    'Sort by': '排序',
    Newest: '最新',
    Oldest: '最老',
    'Recently updated': '最近更新',
    'Published by': '发布者',
    'Search tags': '搜索标签',
    'Search authors': '搜索作者',
    // edit
    Publish: '发布',
    Published: '已发布',
    Publishing: '发布中',
    Unpublish: '撤销发布',
    Unpublished: '撤销发布',
    Unpublishing: '撤销发布中',
    Schedule: '定时',
    Scheduled: '已定时',
    Scheduling: '定时中',
    Unschedule: '撤销定时',
    Unscheduled: '未定时',
    Unscheduling: '撤销定时中',
    Reschedule: '重新定时',
    Rescheduled: '已重新定时',
    Rescheduling: '重新定时中',
    Update: '更新',
    Updated: '已更新',
    Updating: '更新中',
    Save: '保存',
    Saved: '已保存',
    Saving: '保存中',
    Deleted: '已删除',
    Delete: '删除',
    'Updated failed': '更新失败',
    'Unscheduling failed': '取消定时发布失败',
    'Publish failed': '发布失败',
    'Saving failed': '保存失败',
    'Update failed': '更新失败',
    'Scheduling failed': '定时发布失败',
    words: '字',
    'Story Title': '文章标题',
    'Begin writing your story...': '开始写作',
    'Post will go live': '文章将自动发布',
    'Got it': '查看',
    'Upload post image': '上传封面图片',
    'Post URL': '文章地址',
    'View post': '查看文章',
    Preview: '预览',
    'Publish Date': '发布日期',
    'Scheduled Date': '预定发布日期',
    'Use the publish menu to re-schedule': '点击定时按钮更改预定日期',
    Excerpt: '概览',
    Authors: '作者',
    'Meta Data': 'Meta数据',
    'Extra content for search engines': '搜索引擎优化',
    'Code Injection': '代码注入',
    'Add styles/scripts to the header &amp; footer': '添加样式/脚本',
    'Turn this post into a page': '将文章转为页面',
    'Feature this post': '将文章转为专题',
    'Not your first time': '不是新手',
    'Skip these tips': '不再提示',
    'Ok, got it': '知道了',

    'getting-started_title': '开始使用Ghost',
    'getting-started_message': '这是您的管理区域！你可以在这里找到所有的内容、用户和设置。',
    'using-the-editor_title': '使用编辑器',
    'using-the-editor_message': 'Ghost允许使用Markdown快速方便的生成内容。点击<strong>?</strong>了解更多。',
    'static-post_title': '将文章转为页面',
    'static-post_message': '静态页面是区别于文章的页面内容，例如关于我们和联系我们页面。',
    'featured-post_title': '开始专题',
    'featured-post_message': '根据主题不同，主题文章可以通过特殊样式使文章更加重要和醒目。',
    'upload-a-theme_title': '自定义网站样式',
    'upload-a-theme_message': '使用自定义主题，你可以完全控制网站的样式。完整的内容请参考<strong><a href="https://themes.ghost.org" target="_blank">https://themes.ghost.org</a></strong>',

    'Meta Title': 'Meta标题',
    Recommended: '推荐',
    'You’ve used': '已使用',
    'Meta Description': 'Meta描述',
    'Search Engine Result Preview': '搜索引擎结果预览',
    'Post Header': '文章头',
    'Post Footer': '文章尾',
    'Delete Post': '删除文章',

    'Update post status': '更新文章状态',
    'Display this post publicly': '显示到网站',
    'Revert this post to a private draft': '将文章转为草稿',
    'Will be published in': '将发布于',
    'Ready to publish your post': '准备发布',
    'Set it live now': '立即发布',
    'Schedule it for later': '定时发布',
    'Set automatic future publish date': '到时间自动发布',
    Cancel: '取消',
    'Revert to draft': '转为草稿',
    'Do not publish': '不再发布',
    'Schedule for later': '定时发布',
    // tag
    'You haven\'t added any tags yet': '尚未添加任何标签',
    'Add a tag': '添加标签',
    'Are you sure you want to delete this': '确定要删除该',
    'tag?': '标签吗?',
    'post?': '文章吗?',
    'This is permanent! We warned you, k?': '该操作无法撤销，确定吗?',
    'You\'re about to delete': '您即将删除',
    'This tag is attached to': '该标签已使用',
    'Save before you go': '离开前先保存',
    'Are you sure you want to leave this page': '确定离开本页吗',
    Stay: '继续',
    Leave: '离开',
    'New Tag': '新建标签',
    internal: '关键词',
    'Tag Settings': '标签设置',
    Back: '后退',
    'Upload tag image': '上传标签图片',
    Name: '名称',
    URL: '地址',
    Description: '描述',
    Maximum: '最多',
    characters: '字符',
    'Extra content for SEO and social media': 'SEO和社交媒体优化',
    'Delete Tag': '删除标签',
    'Last edited': '最后编辑'
};

export default internation;
